#!/usr/bin/env python3
"""Aggregate coding records into corpus statistics, split by genre.

Reads primary-coder records (coders c1..cN; pilot and double-coder records are
excluded so each deck counts once) and the manifests (for genre and hold-out).
Refuses any hold-out deck. Writes research/corpus-stats.md.

Usage: python3 aggregate.py [--coders c1,c2,...]
"""
from __future__ import annotations

import argparse
import json
import re
import statistics
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CORPUS = Path.home() / "deck-corpus"
MANIFESTS = ("manifest.jsonl", "manifest-aggregators.jsonl", "manifest-public.jsonl")
GROUP = {"banking-board-book": "banking", "consulting-client": "consulting-client",
         "public-sector-client": "consulting-client", "consulting-published": "consulting-published"}
CONTENT_EXCLUDE = {"cover", "disclaimer", "agenda", "divider", "appendix-backup"}


def manifest() -> dict[str, dict]:
    out = {}
    for name in MANIFESTS:
        p = CORPUS / name
        if p.exists():
            for line in p.read_text().splitlines():
                if line.strip():
                    row = json.loads(line)
                    out[row["id"]] = row
    return out


def pct(n: int, d: int) -> str:
    return f"{100 * n / d:.0f}% (n={d})" if d else "—"


def quart(vals: list[float]) -> str:
    if not vals:
        return "—"
    vals = sorted(vals)
    q = statistics.quantiles(vals, n=4) if len(vals) >= 4 else [vals[0], statistics.median(vals), vals[-1]]
    return f"{statistics.median(vals):g} [IQR {q[0]:g}–{q[2]:g}] (n={len(vals)})"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--coders", default="")
    args = ap.parse_args()
    man = manifest()
    coders = [c for c in args.coders.split(",") if c] or sorted(
        p.name for p in (CORPUS / "coding").iterdir() if re.fullmatch(r"c\d+", p.name))
    decks: dict[str, dict] = {}
    for c in coders:
        for f in sorted((CORPUS / "coding" / c).glob("*.json")):
            rec = json.loads(f.read_text())
            row = man.get(rec["deck_id"])
            if row is None:
                continue
            if row.get("holdout"):
                raise SystemExit(f"refusing hold-out deck {rec['deck_id']} (coder {c})")
            decks.setdefault(rec["deck_id"], rec)

    groups: dict[str, list[dict]] = defaultdict(list)
    for deck_id, rec in decks.items():
        g = GROUP.get(man[deck_id]["genre"], man[deck_id]["genre"])
        groups[g].append(rec)
        groups["all"].append(rec)
        if g == "consulting-client" and man[deck_id].get("firm_stratum") == "mbb":
            groups["mbb-client"].append(rec)

    order = ["mbb-client", "consulting-client", "consulting-published", "banking", "all"]
    lines = ["# Corpus statistics (generated by tools/corpus/aggregate.py — do not edit)", "",
             f"Decks: {len(decks)} (derive set only; hold-out excluded). Coders: {', '.join(coders)}.",
             "consulting-client pools private-client and public-sector client deliverables;",
             "mbb-client is its McKinsey/BCG/Bain subset (the best-practice benchmark).", ""]

    def table(title: str, fn) -> None:
        header = "| Metric | " + " | ".join(order) + " |"
        lines.extend([f"## {title}", "", header, "|---|" + "---|" * len(order)])
        for label, per in fn():
            lines.append(f"| {label} | " + " | ".join(per.get(g, "—") for g in order) + " |")
        lines.append("")

    def content(recs):
        return [s for r in recs for s in r["slides"] if s["archetype"] not in CONTENT_EXCLUDE]

    def slide_metrics():
        rows = []
        for label, f in [
            ("Assertion titles (content slides)", lambda ss: pct(sum(s["title_is_assertion"] for s in ss), len(ss))),
            ("Title words, assertion titles",
             lambda ss: quart([s["title_words"] for s in ss if s["title_is_assertion"]])),
            ("Title words, all content titles", lambda ss: quart([s["title_words"] for s in ss if s["title_words"]])),
            ("Title lines", lambda ss: quart([s["title_lines"] for s in ss if s["title_lines"]])),
            ("Unit line under title", lambda ss: pct(sum(s["has_unit_line"] for s in ss), len(ss))),
            ("Source line on chart/table slides", lambda ss: pct(
                sum(s["has_source_line"] for s in ss if s["chart_type"] != "none"),
                sum(1 for s in ss if s["chart_type"] != "none"))),
            ("Numbered notes", lambda ss: pct(sum(s["has_numbered_notes"] for s in ss), len(ss))),
            ("Takeaway / so-what box", lambda ss: pct(sum(s["has_takeaway_box"] for s in ss), len(ss))),
            ("Tracker on content slides", lambda ss: pct(sum(s["has_tracker"] for s in ss), len(ss))),
            ("Accent on one datum (chart slides)", lambda ss: pct(
                sum(s["accent_on_one_datum"] for s in ss if s["chart_type"] != "none"),
                sum(1 for s in ss if s["chart_type"] != "none"))),
            ("Content blocks per slide", lambda ss: quart([s["element_count"] for s in ss])),
            ("Grid columns", lambda ss: quart([s["grid_columns"] for s in ss])),
            ("High text density", lambda ss: pct(sum(s["text_density"] == "high" for s in ss), len(ss))),
        ]:
            rows.append((label, {g: f(content(recs)) for g, recs in groups.items()}))
        return rows

    def deck_metrics():
        rows = []
        for label, f in [
            ("Exec summary present", lambda rs: pct(sum(r["deck"]["exec_summary_position"] > 0 for r in rs), len(rs))),
            ("Exec summary page (when present)", lambda rs: quart(
                [r["deck"]["exec_summary_position"] for r in rs if r["deck"]["exec_summary_position"] > 0])),
            ("Page count", lambda rs: quart([r["deck"]["page_count"] for r in rs])),
            ("Appendix share", lambda rs: quart([round(r["deck"]["appendix_share"], 2) for r in rs])),
            ("Meaningful hues", lambda rs: quart([r["deck"]["palette_count"] for r in rs])),
        ]:
            rows.append((label, {g: f(recs) for g, recs in groups.items()}))
        for field in ("storyline_type", "exec_summary_form", "navigation_system", "divider_style", "footnote_system",
                      "confidentiality_label", "page_aspect", "primary_hue", "title_font_class", "body_font_class"):
            per = {}
            for g, recs in groups.items():
                c = Counter(r["deck"][field] for r in recs)
                per[g] = ", ".join(f"{k} {v}" for k, v in c.most_common(4))
            rows.append((field, per))
        return rows

    def top(field: str, k: int = 12):
        def fn():
            per = {}
            for g, recs in groups.items():
                ss = content(recs) if field != "archetype" else [s for r in recs for s in r["slides"]]
                c = Counter(s[field] for s in ss)
                n = sum(c.values())
                per[g] = "<br>".join(f"{a} {100 * v / n:.0f}%" for a, v in c.most_common(k))
            return [(field, per)]
        return fn

    def callouts():
        per = {}
        for g, recs in groups.items():
            ss = content(recs)
            c = Counter(d for s in ss for d in s["callout_devices"] if d != "none")
            per[g] = "<br>".join(f"{a} {100 * v / len(ss):.0f}%" for a, v in c.most_common(8))
        return [("callout devices (share of content slides)", per)]

    table("Slide level", slide_metrics)
    table("Deck level", deck_metrics)
    table("Archetypes (all sampled pages)", top("archetype", 14))
    table("Chart types (content slides)", top("chart_type", 10))
    table("Callout devices", callouts)
    out = ROOT / "research" / "corpus-stats.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"{len(decks)} decks → {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
